//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace HolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.Maven.ModelsFromOfficialXSD

{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("project", Namespace="http://maven.apache.org/POM/4.0.0", IsNullable=false)]
    public partial class ProjectObjectModel // Model
    {
        
        private string modelVersionField;
        
        private Parent parentField;
        
        private string groupIdField;
        
        private string artifactIdField;
        
        private string versionField;
        
        private string packagingField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string urlField;
        
        private string inceptionYearField;
        
        private Organization organizationField;
        
        private License[] licensesField;
        
        private Developer[] developersField;
        
        private Contributor[] contributorsField;
        
        private MailingList[] mailingListsField;
        
        private Prerequisites prerequisitesField;
        
        private string[] modulesField;
        
        private Scm scmField;
        
        private IssueManagement issueManagementField;
        
        private CiManagement ciManagementField;
        
        private DistributionManagement distributionManagementField;
        
        private ModelProperties propertiesField;
        
        private DependencyManagement dependencyManagementField;
        
        private Dependency[] dependenciesField;
        
        private Repository[] repositoriesField;
        
        private Repository[] pluginRepositoriesField;
        
        private Build buildField;
        
        private ModelReports reportsField;
        
        private Reporting reportingField;
        
        private Profile[] profilesField;
        
        private string childprojecturlinheritappendpathField;
        
        public ProjectObjectModel /* Model */() {
            this.packagingField = "jar";
        }
        
        /// <remarks/>
        public string modelVersion {
            get {
                return this.modelVersionField;
            }
            set {
                this.modelVersionField = value;
            }
        }
        
        /// <remarks/>
        public Parent parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("jar")]
        public string packaging {
            get {
                return this.packagingField;
            }
            set {
                this.packagingField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string inceptionYear {
            get {
                return this.inceptionYearField;
            }
            set {
                this.inceptionYearField = value;
            }
        }
        
        /// <remarks/>
        public Organization organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("license", IsNullable=false)]
        public License[] licenses {
            get {
                return this.licensesField;
            }
            set {
                this.licensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("developer", IsNullable=false)]
        public Developer[] developers {
            get {
                return this.developersField;
            }
            set {
                this.developersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contributor", IsNullable=false)]
        public Contributor[] contributors {
            get {
                return this.contributorsField;
            }
            set {
                this.contributorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mailingList", IsNullable=false)]
        public MailingList[] mailingLists {
            get {
                return this.mailingListsField;
            }
            set {
                this.mailingListsField = value;
            }
        }
        
        /// <remarks/>
        public Prerequisites prerequisites {
            get {
                return this.prerequisitesField;
            }
            set {
                this.prerequisitesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("module", IsNullable=false)]
        public string[] modules {
            get {
                return this.modulesField;
            }
            set {
                this.modulesField = value;
            }
        }
        
        /// <remarks/>
        public Scm scm {
            get {
                return this.scmField;
            }
            set {
                this.scmField = value;
            }
        }
        
        /// <remarks/>
        public IssueManagement issueManagement {
            get {
                return this.issueManagementField;
            }
            set {
                this.issueManagementField = value;
            }
        }
        
        /// <remarks/>
        public CiManagement ciManagement {
            get {
                return this.ciManagementField;
            }
            set {
                this.ciManagementField = value;
            }
        }
        
        /// <remarks/>
        public DistributionManagement distributionManagement {
            get {
                return this.distributionManagementField;
            }
            set {
                this.distributionManagementField = value;
            }
        }
        
        /// <remarks/>
        public ModelProperties properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        public DependencyManagement dependencyManagement {
            get {
                return this.dependencyManagementField;
            }
            set {
                this.dependencyManagementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dependency", IsNullable=false)]
        public Dependency[] dependencies {
            get {
                return this.dependenciesField;
            }
            set {
                this.dependenciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("repository", IsNullable=false)]
        public Repository[] repositories {
            get {
                return this.repositoriesField;
            }
            set {
                this.repositoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("pluginRepository", IsNullable=false)]
        public Repository[] pluginRepositories {
            get {
                return this.pluginRepositoriesField;
            }
            set {
                this.pluginRepositoriesField = value;
            }
        }
        
        /// <remarks/>
        public Build build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
            }
        }
        
        /// <remarks/>
        public ModelReports reports {
            get {
                return this.reportsField;
            }
            set {
                this.reportsField = value;
            }
        }
        
        /// <remarks/>
        public Reporting reporting {
            get {
                return this.reportingField;
            }
            set {
                this.reportingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("profile", IsNullable=false)]
        public Profile[] profiles {
            get {
                return this.profilesField;
            }
            set {
                this.profilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("child.project.url.inherit.append.path")]
        public string childprojecturlinheritappendpath {
            get {
                return this.childprojecturlinheritappendpathField;
            }
            set {
                this.childprojecturlinheritappendpathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Parent {
        
        private string groupIdField;
        
        private string artifactIdField;
        
        private string versionField;
        
        private string relativePathField;
        
        public Parent() {
            this.relativePathField = "../pom.xml";
        }
        
        /// <remarks/>
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("../pom.xml")]
        public string relativePath {
            get {
                return this.relativePathField;
            }
            set {
                this.relativePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class BuildBase {
        
        private string defaultGoalField;
        
        private Resource[] resourcesField;
        
        private Resource[] testResourcesField;
        
        private string directoryField;
        
        private string finalNameField;
        
        private string[] filtersField;
        
        private PluginManagement pluginManagementField;
        
        private Plugin[] pluginsField;
        
        /// <remarks/>
        public string defaultGoal {
            get {
                return this.defaultGoalField;
            }
            set {
                this.defaultGoalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable=false)]
        public Resource[] resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("testResource", IsNullable=false)]
        public Resource[] testResources {
            get {
                return this.testResourcesField;
            }
            set {
                this.testResourcesField = value;
            }
        }
        
        /// <remarks/>
        public string directory {
            get {
                return this.directoryField;
            }
            set {
                this.directoryField = value;
            }
        }
        
        /// <remarks/>
        public string finalName {
            get {
                return this.finalNameField;
            }
            set {
                this.finalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("filter", IsNullable=false)]
        public string[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        public PluginManagement pluginManagement {
            get {
                return this.pluginManagementField;
            }
            set {
                this.pluginManagementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("plugin", IsNullable=false)]
        public Plugin[] plugins {
            get {
                return this.pluginsField;
            }
            set {
                this.pluginsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Resource {
        
        private string targetPathField;
        
        private string filteringField;
        
        private string directoryField;
        
        private string[] includesField;
        
        private string[] excludesField;
        
        /// <remarks/>
        public string targetPath {
            get {
                return this.targetPathField;
            }
            set {
                this.targetPathField = value;
            }
        }
        
        /// <remarks/>
        public string filtering {
            get {
                return this.filteringField;
            }
            set {
                this.filteringField = value;
            }
        }
        
        /// <remarks/>
        public string directory {
            get {
                return this.directoryField;
            }
            set {
                this.directoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("include", IsNullable=false)]
        public string[] includes {
            get {
                return this.includesField;
            }
            set {
                this.includesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("exclude", IsNullable=false)]
        public string[] excludes {
            get {
                return this.excludesField;
            }
            set {
                this.excludesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class PluginManagement {
        
        private Plugin[] pluginsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("plugin", IsNullable=false)]
        public Plugin[] plugins {
            get {
                return this.pluginsField;
            }
            set {
                this.pluginsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Plugin {
        
        private string groupIdField;
        
        private string artifactIdField;
        
        private string versionField;
        
        private string extensionsField;
        
        private PluginExecution[] executionsField;
        
        private Dependency[] dependenciesField;
        
        private PluginGoals goalsField;
        
        private string inheritedField;
        
        private PluginConfiguration configurationField;
        
        public Plugin() {
            this.groupIdField = "org.apache.maven.plugins";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("org.apache.maven.plugins")]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("execution", IsNullable=false)]
        public PluginExecution[] executions {
            get {
                return this.executionsField;
            }
            set {
                this.executionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dependency", IsNullable=false)]
        public Dependency[] dependencies {
            get {
                return this.dependenciesField;
            }
            set {
                this.dependenciesField = value;
            }
        }
        
        /// <remarks/>
        public PluginGoals goals {
            get {
                return this.goalsField;
            }
            set {
                this.goalsField = value;
            }
        }
        
        /// <remarks/>
        public string inherited {
            get {
                return this.inheritedField;
            }
            set {
                this.inheritedField = value;
            }
        }
        
        /// <remarks/>
        public PluginConfiguration configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class PluginExecution {
        
        private string idField;
        
        private string phaseField;
        
        private string[] goalsField;
        
        private string inheritedField;
        
        private PluginExecutionConfiguration configurationField;
        
        public PluginExecution() {
            this.idField = "default";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("default")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string phase {
            get {
                return this.phaseField;
            }
            set {
                this.phaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("goal", IsNullable=false)]
        public string[] goals {
            get {
                return this.goalsField;
            }
            set {
                this.goalsField = value;
            }
        }
        
        /// <remarks/>
        public string inherited {
            get {
                return this.inheritedField;
            }
            set {
                this.inheritedField = value;
            }
        }
        
        /// <remarks/>
        public PluginExecutionConfiguration configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class PluginExecutionConfiguration {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Dependency {
        
        private string groupIdField;
        
        private string artifactIdField;
        
        private string versionField;
        
        private string typeField;
        
        private string classifierField;
        
        private string scopeField;
        
        private string systemPathField;
        
        private Exclusion[] exclusionsField;
        
        private string optionalField;
        
        public Dependency() {
            this.typeField = "jar";
        }
        
        /// <remarks/>
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("jar")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string classifier {
            get {
                return this.classifierField;
            }
            set {
                this.classifierField = value;
            }
        }
        
        /// <remarks/>
        public string scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        public string systemPath {
            get {
                return this.systemPathField;
            }
            set {
                this.systemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("exclusion", IsNullable=false)]
        public Exclusion[] exclusions {
            get {
                return this.exclusionsField;
            }
            set {
                this.exclusionsField = value;
            }
        }
        
        /// <remarks/>
        public string optional {
            get {
                return this.optionalField;
            }
            set {
                this.optionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Exclusion {
        
        private string artifactIdField;
        
        private string groupIdField;
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class PluginGoals {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class PluginConfiguration {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ActivationFile {
        
        private string missingField;
        
        private string existsField;
        
        /// <remarks/>
        public string missing {
            get {
                return this.missingField;
            }
            set {
                this.missingField = value;
            }
        }
        
        /// <remarks/>
        public string exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ActivationProperty {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ActivationOS {
        
        private string nameField;
        
        private string familyField;
        
        private string archField;
        
        private string versionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        public string arch {
            get {
                return this.archField;
            }
            set {
                this.archField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Activation {
        
        private bool activeByDefaultField;
        
        private string jdkField;
        
        private ActivationOS osField;
        
        private ActivationProperty propertyField;
        
        private ActivationFile fileField;
        
        public Activation() {
            this.activeByDefaultField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool activeByDefault {
            get {
                return this.activeByDefaultField;
            }
            set {
                this.activeByDefaultField = value;
            }
        }
        
        /// <remarks/>
        public string jdk {
            get {
                return this.jdkField;
            }
            set {
                this.jdkField = value;
            }
        }
        
        /// <remarks/>
        public ActivationOS os {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        public ActivationProperty property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        public ActivationFile file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Profile {
        
        private string idField;
        
        private Activation activationField;
        
        private BuildBase buildField;
        
        private string[] modulesField;
        
        private DistributionManagement distributionManagementField;
        
        private ProfileProperties propertiesField;
        
        private DependencyManagement dependencyManagementField;
        
        private Dependency[] dependenciesField;
        
        private Repository[] repositoriesField;
        
        private Repository[] pluginRepositoriesField;
        
        private ProfileReports reportsField;
        
        private Reporting reportingField;
        
        public Profile() {
            this.idField = "default";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("default")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Activation activation {
            get {
                return this.activationField;
            }
            set {
                this.activationField = value;
            }
        }
        
        /// <remarks/>
        public BuildBase build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("module", IsNullable=false)]
        public string[] modules {
            get {
                return this.modulesField;
            }
            set {
                this.modulesField = value;
            }
        }
        
        /// <remarks/>
        public DistributionManagement distributionManagement {
            get {
                return this.distributionManagementField;
            }
            set {
                this.distributionManagementField = value;
            }
        }
        
        /// <remarks/>
        public ProfileProperties properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        public DependencyManagement dependencyManagement {
            get {
                return this.dependencyManagementField;
            }
            set {
                this.dependencyManagementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dependency", IsNullable=false)]
        public Dependency[] dependencies {
            get {
                return this.dependenciesField;
            }
            set {
                this.dependenciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("repository", IsNullable=false)]
        public Repository[] repositories {
            get {
                return this.repositoriesField;
            }
            set {
                this.repositoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("pluginRepository", IsNullable=false)]
        public Repository[] pluginRepositories {
            get {
                return this.pluginRepositoriesField;
            }
            set {
                this.pluginRepositoriesField = value;
            }
        }
        
        /// <remarks/>
        public ProfileReports reports {
            get {
                return this.reportsField;
            }
            set {
                this.reportsField = value;
            }
        }
        
        /// <remarks/>
        public Reporting reporting {
            get {
                return this.reportingField;
            }
            set {
                this.reportingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class DistributionManagement {
        
        private DeploymentRepository repositoryField;
        
        private DeploymentRepository snapshotRepositoryField;
        
        private Site siteField;
        
        private string downloadUrlField;
        
        private Relocation relocationField;
        
        private string statusField;
        
        /// <remarks/>
        public DeploymentRepository repository {
            get {
                return this.repositoryField;
            }
            set {
                this.repositoryField = value;
            }
        }
        
        /// <remarks/>
        public DeploymentRepository snapshotRepository {
            get {
                return this.snapshotRepositoryField;
            }
            set {
                this.snapshotRepositoryField = value;
            }
        }
        
        /// <remarks/>
        public Site site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string downloadUrl {
            get {
                return this.downloadUrlField;
            }
            set {
                this.downloadUrlField = value;
            }
        }
        
        /// <remarks/>
        public Relocation relocation {
            get {
                return this.relocationField;
            }
            set {
                this.relocationField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class DeploymentRepository {
        
        private bool uniqueVersionField;
        
        private RepositoryPolicy releasesField;
        
        private RepositoryPolicy snapshotsField;
        
        private string idField;
        
        private string nameField;
        
        private string urlField;
        
        private string layoutField;
        
        public DeploymentRepository() {
            this.uniqueVersionField = true;
            this.layoutField = "default";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool uniqueVersion {
            get {
                return this.uniqueVersionField;
            }
            set {
                this.uniqueVersionField = value;
            }
        }
        
        /// <remarks/>
        public RepositoryPolicy releases {
            get {
                return this.releasesField;
            }
            set {
                this.releasesField = value;
            }
        }
        
        /// <remarks/>
        public RepositoryPolicy snapshots {
            get {
                return this.snapshotsField;
            }
            set {
                this.snapshotsField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("default")]
        public string layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class RepositoryPolicy {
        
        private string enabledField;
        
        private string updatePolicyField;
        
        private string checksumPolicyField;
        
        /// <remarks/>
        public string enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public string updatePolicy {
            get {
                return this.updatePolicyField;
            }
            set {
                this.updatePolicyField = value;
            }
        }
        
        /// <remarks/>
        public string checksumPolicy {
            get {
                return this.checksumPolicyField;
            }
            set {
                this.checksumPolicyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Site {
        
        private string idField;
        
        private string nameField;
        
        private string urlField;
        
        private string childsiteurlinheritappendpathField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("child.site.url.inherit.append.path")]
        public string childsiteurlinheritappendpath {
            get {
                return this.childsiteurlinheritappendpathField;
            }
            set {
                this.childsiteurlinheritappendpathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Relocation {
        
        private string groupIdField;
        
        private string artifactIdField;
        
        private string versionField;
        
        private string messageField;
        
        /// <remarks/>
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ProfileProperties {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class DependencyManagement {
        
        private Dependency[] dependenciesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dependency", IsNullable=false)]
        public Dependency[] dependencies {
            get {
                return this.dependenciesField;
            }
            set {
                this.dependenciesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Repository {
        
        private RepositoryPolicy releasesField;
        
        private RepositoryPolicy snapshotsField;
        
        private string idField;
        
        private string nameField;
        
        private string urlField;
        
        private string layoutField;
        
        public Repository() {
            this.layoutField = "default";
        }
        
        /// <remarks/>
        public RepositoryPolicy releases {
            get {
                return this.releasesField;
            }
            set {
                this.releasesField = value;
            }
        }
        
        /// <remarks/>
        public RepositoryPolicy snapshots {
            get {
                return this.snapshotsField;
            }
            set {
                this.snapshotsField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("default")]
        public string layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ProfileReports {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Reporting {
        
        private string excludeDefaultsField;
        
        private string outputDirectoryField;
        
        private ReportPlugin[] pluginsField;
        
        /// <remarks/>
        public string excludeDefaults {
            get {
                return this.excludeDefaultsField;
            }
            set {
                this.excludeDefaultsField = value;
            }
        }
        
        /// <remarks/>
        public string outputDirectory {
            get {
                return this.outputDirectoryField;
            }
            set {
                this.outputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("plugin", IsNullable=false)]
        public ReportPlugin[] plugins {
            get {
                return this.pluginsField;
            }
            set {
                this.pluginsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ReportPlugin {
        
        private string groupIdField;
        
        private string artifactIdField;
        
        private string versionField;
        
        private ReportSet[] reportSetsField;
        
        private string inheritedField;
        
        private ReportPluginConfiguration configurationField;
        
        public ReportPlugin() {
            this.groupIdField = "org.apache.maven.plugins";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("org.apache.maven.plugins")]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("reportSet", IsNullable=false)]
        public ReportSet[] reportSets {
            get {
                return this.reportSetsField;
            }
            set {
                this.reportSetsField = value;
            }
        }
        
        /// <remarks/>
        public string inherited {
            get {
                return this.inheritedField;
            }
            set {
                this.inheritedField = value;
            }
        }
        
        /// <remarks/>
        public ReportPluginConfiguration configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ReportSet {
        
        private string idField;
        
        private string[] reportsField;
        
        private string inheritedField;
        
        private ReportSetConfiguration configurationField;
        
        public ReportSet() {
            this.idField = "default";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("default")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("report", IsNullable=false)]
        public string[] reports {
            get {
                return this.reportsField;
            }
            set {
                this.reportsField = value;
            }
        }
        
        /// <remarks/>
        public string inherited {
            get {
                return this.inheritedField;
            }
            set {
                this.inheritedField = value;
            }
        }
        
        /// <remarks/>
        public ReportSetConfiguration configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ReportSetConfiguration {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ReportPluginConfiguration {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Extension {
        
        private string groupIdField;
        
        private string artifactIdField;
        
        private string versionField;
        
        /// <remarks/>
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Build {
        
        private string sourceDirectoryField;
        
        private string scriptSourceDirectoryField;
        
        private string testSourceDirectoryField;
        
        private string outputDirectoryField;
        
        private string testOutputDirectoryField;
        
        private Extension[] extensionsField;
        
        private string defaultGoalField;
        
        private Resource[] resourcesField;
        
        private Resource[] testResourcesField;
        
        private string directoryField;
        
        private string finalNameField;
        
        private string[] filtersField;
        
        private PluginManagement pluginManagementField;
        
        private Plugin[] pluginsField;
        
        /// <remarks/>
        public string sourceDirectory {
            get {
                return this.sourceDirectoryField;
            }
            set {
                this.sourceDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string scriptSourceDirectory {
            get {
                return this.scriptSourceDirectoryField;
            }
            set {
                this.scriptSourceDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string testSourceDirectory {
            get {
                return this.testSourceDirectoryField;
            }
            set {
                this.testSourceDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string outputDirectory {
            get {
                return this.outputDirectoryField;
            }
            set {
                this.outputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string testOutputDirectory {
            get {
                return this.testOutputDirectoryField;
            }
            set {
                this.testOutputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("extension", IsNullable=false)]
        public Extension[] extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        public string defaultGoal {
            get {
                return this.defaultGoalField;
            }
            set {
                this.defaultGoalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable=false)]
        public Resource[] resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("testResource", IsNullable=false)]
        public Resource[] testResources {
            get {
                return this.testResourcesField;
            }
            set {
                this.testResourcesField = value;
            }
        }
        
        /// <remarks/>
        public string directory {
            get {
                return this.directoryField;
            }
            set {
                this.directoryField = value;
            }
        }
        
        /// <remarks/>
        public string finalName {
            get {
                return this.finalNameField;
            }
            set {
                this.finalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("filter", IsNullable=false)]
        public string[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        public PluginManagement pluginManagement {
            get {
                return this.pluginManagementField;
            }
            set {
                this.pluginManagementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("plugin", IsNullable=false)]
        public Plugin[] plugins {
            get {
                return this.pluginsField;
            }
            set {
                this.pluginsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Notifier {
        
        private string typeField;
        
        private bool sendOnErrorField;
        
        private bool sendOnFailureField;
        
        private bool sendOnSuccessField;
        
        private bool sendOnWarningField;
        
        private string addressField;
        
        private NotifierConfiguration configurationField;
        
        public Notifier() {
            this.typeField = "mail";
            this.sendOnErrorField = true;
            this.sendOnFailureField = true;
            this.sendOnSuccessField = true;
            this.sendOnWarningField = true;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("mail")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool sendOnError {
            get {
                return this.sendOnErrorField;
            }
            set {
                this.sendOnErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool sendOnFailure {
            get {
                return this.sendOnFailureField;
            }
            set {
                this.sendOnFailureField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool sendOnSuccess {
            get {
                return this.sendOnSuccessField;
            }
            set {
                this.sendOnSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool sendOnWarning {
            get {
                return this.sendOnWarningField;
            }
            set {
                this.sendOnWarningField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public NotifierConfiguration configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class NotifierConfiguration {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class CiManagement {
        
        private string systemField;
        
        private string urlField;
        
        private Notifier[] notifiersField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("notifier", IsNullable=false)]
        public Notifier[] notifiers {
            get {
                return this.notifiersField;
            }
            set {
                this.notifiersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class IssueManagement {
        
        private string systemField;
        
        private string urlField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Scm {
        
        private string connectionField;
        
        private string developerConnectionField;
        
        private string tagField;
        
        private string urlField;
        
        private string childscmconnectioninheritappendpathField;
        
        private string childscmdeveloperConnectioninheritappendpathField;
        
        private string childscmurlinheritappendpathField;
        
        public Scm() {
            this.tagField = "HEAD";
        }
        
        /// <remarks/>
        public string connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        public string developerConnection {
            get {
                return this.developerConnectionField;
            }
            set {
                this.developerConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("HEAD")]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("child.scm.connection.inherit.append.path")]
        public string childscmconnectioninheritappendpath {
            get {
                return this.childscmconnectioninheritappendpathField;
            }
            set {
                this.childscmconnectioninheritappendpathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("child.scm.developerConnection.inherit.append.path")]
        public string childscmdeveloperConnectioninheritappendpath {
            get {
                return this.childscmdeveloperConnectioninheritappendpathField;
            }
            set {
                this.childscmdeveloperConnectioninheritappendpathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("child.scm.url.inherit.append.path")]
        public string childscmurlinheritappendpath {
            get {
                return this.childscmurlinheritappendpathField;
            }
            set {
                this.childscmurlinheritappendpathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Prerequisites {
        
        private string mavenField;
        
        public Prerequisites() {
            this.mavenField = "2.0";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("2.0")]
        public string maven {
            get {
                return this.mavenField;
            }
            set {
                this.mavenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class MailingList {
        
        private string nameField;
        
        private string subscribeField;
        
        private string unsubscribeField;
        
        private string postField;
        
        private string archiveField;
        
        private string[] otherArchivesField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string subscribe {
            get {
                return this.subscribeField;
            }
            set {
                this.subscribeField = value;
            }
        }
        
        /// <remarks/>
        public string unsubscribe {
            get {
                return this.unsubscribeField;
            }
            set {
                this.unsubscribeField = value;
            }
        }
        
        /// <remarks/>
        public string post {
            get {
                return this.postField;
            }
            set {
                this.postField = value;
            }
        }
        
        /// <remarks/>
        public string archive {
            get {
                return this.archiveField;
            }
            set {
                this.archiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("otherArchive", IsNullable=false)]
        public string[] otherArchives {
            get {
                return this.otherArchivesField;
            }
            set {
                this.otherArchivesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Contributor {
        
        private string nameField;
        
        private string emailField;
        
        private string urlField;
        
        private string organizationField;
        
        private string organizationUrlField;
        
        private string[] rolesField;
        
        private string timezoneField;
        
        private ContributorProperties propertiesField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public string organizationUrl {
            get {
                return this.organizationUrlField;
            }
            set {
                this.organizationUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("role", IsNullable=false)]
        public string[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        public string timezone {
            get {
                return this.timezoneField;
            }
            set {
                this.timezoneField = value;
            }
        }
        
        /// <remarks/>
        public ContributorProperties properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ContributorProperties {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Developer {
        
        private string idField;
        
        private string nameField;
        
        private string emailField;
        
        private string urlField;
        
        private string organizationField;
        
        private string organizationUrlField;
        
        private string[] rolesField;
        
        private string timezoneField;
        
        private DeveloperProperties propertiesField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public string organizationUrl {
            get {
                return this.organizationUrlField;
            }
            set {
                this.organizationUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("role", IsNullable=false)]
        public string[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        public string timezone {
            get {
                return this.timezoneField;
            }
            set {
                this.timezoneField = value;
            }
        }
        
        /// <remarks/>
        public DeveloperProperties properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class DeveloperProperties {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class License {
        
        private string nameField;
        
        private string urlField;
        
        private string distributionField;
        
        private string commentsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string distribution {
            get {
                return this.distributionField;
            }
            set {
                this.distributionField = value;
            }
        }
        
        /// <remarks/>
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class Organization {
        
        private string nameField;
        
        private string urlField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ModelProperties {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://maven.apache.org/POM/4.0.0")]
    public partial class ModelReports {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
}
