//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace HolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.Maven.Maven.Repositories.MavenCentral.Artifact {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class metadata {
        
        private string groupIdField;
        
        private string artifactIdField;
        
        private metadataVersioning versioningField;
        
        /// <remarks/>
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public string artifactId {
            get {
                return this.artifactIdField;
            }
            set {
                this.artifactIdField = value;
            }
        }
        
        /// <remarks/>
        public metadataVersioning versioning {
            get {
                return this.versioningField;
            }
            set {
                this.versioningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class metadataVersioning {
        
        private string latestField;
        
        private string releaseField;
        
        private string[] versionsField;
        
        private ulong lastUpdatedField;
        
        /// <remarks/>
        public string latest {
            get {
                return this.latestField;
            }
            set {
                this.latestField = value;
            }
        }
        
        /// <remarks/>
        public string release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("version", IsNullable=false)]
        public string[] versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
            }
        }
        
        /// <remarks/>
        public ulong lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
    }
}
