using Microsoft.AspNetCore.Mvc;

using Newtonsoft.Json;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuHolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.BinderatorickType;
//
//    var config = Config.FromJson(jsonString);

namespace HolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.Binderator.QuickType
{
    // POCO class with Metadata for Buddy Class containing attributes
    // <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
    // using Microsoft.AspNetCore.Mvc;
    [ModelMetadataType(typeof(JSON.ConfigRoot))]
    public partial class ConfigRoot
    {
        public static ConfigRoot Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<ConfigRoot>(json);
        }

    }
}

namespace HolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.Binderator.QuickType.JSON
{
    public partial class ConfigRoot
    {
        [JsonProperty("mavenRepositoryType")]
        public string MavenRepositoryType
        {
            get;
            set;
        }

        [JsonProperty("slnFile")]
        public string SlnFile
        {
            get;
            set;
        }

        [JsonProperty("additionalProjects")]
        public string[] AdditionalProjects
        {
            get;
            set;
        }

        [JsonProperty("templates")]
        public Template[] Templates
        {
            get;
            set;
        }

        [JsonProperty("artifacts")]
        public Artifact[] Artifacts
        {
            get;
            set;
        }
    }

}
