using Microsoft.AspNetCore.Mvc;

using Newtonsoft.Json;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuHolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.BinderatorickType;
//
//    var config = Config.FromJson(jsonString);

namespace HolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.Binderator.QuickType
{
    // POCO class with Metadata for Buddy Class containing attributes
    // <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
    // using Microsoft.AspNetCore.Mvc;
    [ModelMetadataType(typeof(JSON.Template))]
    public partial class Template
    {
        public static Template Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<Template>(json);
        }

    }
}

namespace HolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.Binderator.QuickType.JSON
{
    public partial class Template
    {
        [JsonProperty("templateFile")]
        public string TemplateFile
        {
            get;
            set;
        }

        [JsonProperty("outputFileRule")]
        public string OutputFileRule
        {
            get;
            set;
        }
    }
}
