//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//

using System.Collections.Generic;
using System.Xml.Serialization;

namespace HolisticWare.Xamarin.Tools.NuGet.NuSpec.Generated.Microsoft
{
	// using System.Xml.Serialization;
	// XmlSerializer serializer = new XmlSerializer(typeof(Package));
	// using (StringReader reader = new StringReader(xml))
	// {
	//    var test = (Package)serializer.Deserialize(reader);
	// }

	[XmlRoot(ElementName = "license")]
	public class License
	{

		[XmlAttribute(AttributeName = "type")] public string Type { get; set; }

		[XmlText] public string Text { get; set; }
	}

	[XmlRoot(ElementName = "repository")]
	public class Repository
	{

		[XmlAttribute(AttributeName = "type")] public string Type { get; set; }

		[XmlAttribute(AttributeName = "url")] public string Url { get; set; }

		[XmlAttribute(AttributeName = "branch")]
		public string Branch { get; set; }

		[XmlAttribute(AttributeName = "commit")]
		public string Commit { get; set; }
	}

	[XmlRoot(ElementName = "dependency")]
	public class Dependency
	{

		[XmlAttribute(AttributeName = "id")] public string Id { get; set; }

		[XmlAttribute(AttributeName = "version")]
		public string Version { get; set; }

		[XmlAttribute(AttributeName = "include")]
		public string Include { get; set; }
	}

	[XmlRoot(ElementName = "group")]
	public class Group
	{

		[XmlElement(ElementName = "dependency")]
		public List<Dependency> Dependency { get; set; }

		[XmlAttribute(AttributeName = "targetFramework")]
		public string TargetFramework { get; set; }
	}

	[XmlRoot(ElementName = "dependencies")]
	public class Dependencies
	{

		[XmlElement(ElementName = "group")] public Group Group { get; set; }
	}

	[XmlRoot(ElementName = "frameworkAssembly")]
	public class FrameworkAssembly
	{

		[XmlAttribute(AttributeName = "assemblyName")]
		public string AssemblyName { get; set; }

		[XmlAttribute(AttributeName = "targetFramework")]
		public string TargetFramework { get; set; }
	}

	[XmlRoot(ElementName = "frameworkAssemblies")]
	public class FrameworkAssemblies
	{

		[XmlElement(ElementName = "frameworkAssembly")]
		public FrameworkAssembly FrameworkAssembly { get; set; }
	}

	[XmlRoot(ElementName = "metadata")]
	public class Metadata
	{

		[XmlElement(ElementName = "id")] public string Id { get; set; }

		[XmlElement(ElementName = "version")] public string Version { get; set; }

		[XmlElement(ElementName = "title")] public string Title { get; set; }

		[XmlElement(ElementName = "authors")] public string Authors { get; set; }

		[XmlElement(ElementName = "owners")] public string Owners { get; set; }

		[XmlElement(ElementName = "requireLicenseAcceptance")]
		public bool RequireLicenseAcceptance { get; set; }

		[XmlElement(ElementName = "license")] public License License { get; set; }

		[XmlElement(ElementName = "licenseUrl")]
		public string LicenseUrl { get; set; }

		[XmlElement(ElementName = "projectUrl")]
		public string ProjectUrl { get; set; }

		[XmlElement(ElementName = "iconUrl")] public string IconUrl { get; set; }

		[XmlElement(ElementName = "description")]
		public string Description { get; set; }

		[XmlElement(ElementName = "copyright")]
		public string Copyright { get; set; }

		[XmlElement(ElementName = "tags")] public string Tags { get; set; }

		[XmlElement(ElementName = "repository")]
		public Repository Repository { get; set; }

		[XmlElement(ElementName = "dependencies")]
		public Dependencies Dependencies { get; set; }

		[XmlElement(ElementName = "frameworkAssemblies")]
		public FrameworkAssemblies FrameworkAssemblies { get; set; }
	}

	[XmlRoot(ElementName = "package")]
	public class Package
	{

		[XmlElement(ElementName = "metadata")] public Metadata Metadata { get; set; }

		[XmlAttribute(AttributeName = "xmlns")]
		public string Xmlns { get; set; }

		[XmlText] public string Text { get; set; }
	}

}
