using Newtonsoft.Json;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuHolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.BinderatorickType;
//
//    var config = Config.FromJson(jsonString);

namespace HolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.Binderator.QuickType
{

    public partial class ConfigRoot
    {
        public string MavenRepositoryType
        {
            get;
            set;
        }

        public string SlnFile
        {
            get;
            set;
        }

        public string[] AdditionalProjects
        {
            get;
            set;
        }

        public Template[] Templates
        {
            get;
            set;
        }

        public Artifact[] Artifacts
        {
            get;
            set;
        }
    }
}
