using Newtonsoft.Json;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuHolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.BinderatorickType;
//
//    var config = Config.FromJson(jsonString);

namespace HolisticWare.Xamarin.Tools.Bindings.XamarinAndroid.FassBinderMeister.Binderator.QuickType
{
    public static class Serializer
    {
        public static string ToJson(this BinderatorConfigDownloader[] self)
            =>
            JsonConvert.SerializeObject(self, Converter.Settings);
    }
}
